### ISSUE TITLE
Have the ability to to sync images from docker hub to an on-premise registry

### ISSUE THREAD

**Issue by nvpnathan** [tkrausjr/image-mover#1]

**Comment by tkrausjr** [comment]
This should be simple. Need to add an input flag to specify a list instead of a registry.  Should be done by next week.

**Comment by tkrausjr** [comment]
You can now use the " -i " flag to specify a LIST of Images.

python3 image-mover.py -i nginx:latest,tomcat -m sync -d domain.com -u user -p password -n library --secure
