### ISSUE TITLE
Getting this traceback error trying to sync from docker hub to local registry

### ISSUE THREAD

**Issue by nvpnathan** [tkrausjr/image-mover#3]
python3 image-mover.py -i mysql:latest,redis:lastest -m sync -d harbor.corp.local/core

Image List provided as a flag. Images = ['mysql:latest', 'redis:lastest']
mysql:latest
Tag exists, tag =  latest
redis:lastest
Tag exists, tag =  lastest

 *****************************************
 args Mode = sync
 args Source Registry = None
 args Source Images = mysql:latest,redis:lastest
 args Destination Registry =harbor.corp.local/core
 *****************************************

Querying Destination Registry Host = harbor.corp.local/core
--Found Repositories on server
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "image-mover.py", line 330, in <module>
    dst_repos = get_registry_images(dst_registry_proto, args.destination_registry)
  File "image-mover.py", line 71, in get_registry_images
    responseJson = response.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tkrausjr** [comment]
Thanks I just updated the code.  There were a couple of issues with Harbor that I had to fix. Harbor connections require SSL so I added a flag --secure to specify a secure connection.   Harbor also requires a Namespace or Project. The default is library so I updated the code to support this and added another parameter to specify the namespace which must already exist in Harbor.

Tested below is working. Let me know if you have any more issues.

root@ubu01-jumphost:~/github/image-mover# python3 image-mover.py -i nginx:latest,tomcat -m sync -d harbor.domain.com -u username -p password -n library --secure
